apiVersion: v1
kind: Service
metadata:
  name: geth
  namespace: ethereum
  labels:
    app: geth
spec:
  type: ClusterIP
  ports:
    - port: 8545
      targetPort: 8545
      protocol: TCP
      name: http-rpc
    - port: 8546
      targetPort: 8546
      protocol: TCP
      name: ws-rpc
    - port: 8551
      targetPort: 8551
      protocol: TCP
      name: authrpc
    - port: 30303
      targetPort: 30303
      protocol: TCP
      name: p2p-tcp
    - port: 30303
      targetPort: 30303
      protocol: UDP
      name: p2p-udp
    - port: 6060
      targetPort: 6060
      protocol: TCP
      name: metrics
  selector:
    app: geth
---
apiVersion: v1
kind: Service
metadata:
  name: geth-p2p
  namespace: ethereum
  labels:
    app: geth
spec:
  type: NodePort
  ports:
    - port: 30303
      targetPort: 30303
      protocol: TCP
      name: p2p-tcp
    - port: 30303
      targetPort: 30303
      protocol: UDP
      name: p2p-udp
  selector:
    app: geth
