apiVersion: v1
kind: Service
metadata:
  name: prysm-beacon
  namespace: ethereum
  labels:
    app: prysm-beacon
spec:
  type: ClusterIP
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
      name: http-rpc
    - port: 3500
      targetPort: 3500
      protocol: TCP
      name: grpc
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: metrics
    - port: 13000
      targetPort: 13000
      protocol: TCP
      name: p2p-tcp
    - port: 12000
      targetPort: 12000
      protocol: UDP
      name: p2p-udp
  selector:
    app: prysm-beacon
---
apiVersion: v1
kind: Service
metadata:
  name: prysm-beacon-p2p
  namespace: ethereum
  labels:
    app: prysm-beacon
spec:
  type: NodePort
  ports:
    - port: 13000
      targetPort: 13000
      protocol: TCP
      name: p2p-tcp
    - port: 12000
      targetPort: 12000
      protocol: UDP
      name: p2p-udp
  selector:
    app: prysm-beacon
