apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.ethereum }}
  labels:
    name: {{ .Values.namespace.ethereum }}
---
{{- if .Values.monitoring.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.monitoring }}
  labels:
    name: {{ .Values.namespace.monitoring }}
{{- end }}
