apiVersion: v2
name: ethereum-node
description: A Helm chart for deploying Ethereum execution and consensus clients on Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - ethereum
  - geth
  - prysm
  - blockchain
  - monitoring
maintainers:
  - name: debbie-k8s
home: https://github.com/ethereum/go-ethereum
sources:
  - https://github.com/ethereum/go-ethereum
  - https://github.com/prysmaticlabs/prysm
